---
ALLOW_INDEXING: true
ENABLE_SENTRY: true
SENTRY_ENVIRONMENT: production
ENABLE_PERSONAS: false
ENABLE_FAKE_TRS_API: false
ENABLE_DIRECT_SCHOOL_DFE_SIGN_IN: true
ENABLE_BLAZER: true
ENABLE_API: false
ENABLE_MIGRATION_TESTING: false
ENABLE_MIGRATION_INTERFACE: false
ENABLE_SCHOOLS_INTERFACE: true
ENABLE_INCIDENT_BANNER: false
ENABLE_MAINTENANCE_BANNER: true
ENABLE_APPROPRIATE_BODY_RECORDS_TO_REVIEW: false
ENABLE_HUBS: false
DFE_SIGN_IN_API_AUDIENCE: signin.education.gov.uk
DFE_SIGN_IN_PROFILE: "https://profile.signin.education.gov.uk"
DFE_SIGN_IN_API_BASE_URL: "https://api.signin.education.gov.uk"
DFE_SIGN_IN_CLIENT_ID: RegisterECTs
DFE_SIGN_IN_ISSUER: "https://oidc.signin.education.gov.uk"
DFE_SIGN_IN_REDIRECT_URI: "https://www.register-early-career-teachers.education.gov.uk/auth/dfe/callback"
DFE_SIGN_IN_SIGN_OUT_REDIRECT_URI: "https://www.register-early-career-teachers.education.gov.uk/sign-out"
SERVICE_URL: "https://www.register-early-career-teachers.education.gov.uk"
DFE_ANALYTICS_ENABLED: true
TRS_API_BASE_URL: "https://teacher-qualifications-api.education.gov.uk"
TRS_API_VERSION: "20260120"
RAILS_ENV: production
MAX_SESSION_IDLE_TIME: 7200
